/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'LESLIE' at '02-08-16 12:46' with Gradle 2.14
 *
 * @author LESLIE, @date 02-08-16 12:46
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
